package com.ganten.market.common.pojo;

public enum CommandEventType {
    COMMAND_EVENT_TYPE_UNSPECIFIED, COMMAND_EVENT_TYPE_ORDER_OPERATION, COMMAND_EVENT_TYPE_SNAPSHOT, COMMAND_EVENT_TYPE_ORDERBOOK_SYNC, COMMAND_EVENT_TYPE_TRANSITION
}
