package com.ganten.market.common.pojo;

public enum OrderOperationType {
    ORDER_OPERATION_TYPE_UNSPECIFIED, ORDER_OPERATION_TYPE_PLACE, ORDER_OPERATION_TYPE_REPLACE, ORDER_OPERATION_TYPE_CANCEL, ORDER_OPERATION_TYPE_STATE_TRANSIT, ORDER_OPERATION_TYPE_CHANGE_ORDER_LIMIT_PERCENTILE
}
