package com.ganten.market.common.pojo;

public enum ResultEventType {
    RESULT_EVENT_TYPE_UNSPECIFIED, RESULT_EVENT_TYPE_TICK, RESULT_EVENT_TYPE_TRADE, RESULT_EVENT_TYPE_ORDERBOOK, RESULT_EVENT_TYPE_DIFFORDERBOOK, RESULT_EVENT_TYPE_DIFFORDERBOOKALL, RESULT_EVENT_TYPE_SNAPSHOT;
}
